// Generated by build script, do not edit!
#ifndef RC_INVOKED

#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies ApS";
    extern const char* const UnityCopyright = "(c) 2022 Unity Technologies ApS. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/buildslave/unity/build";

    extern const char* const UnityVersion = "2022.1.11f1";
    extern const char* const UnityVersionDigits = "2022.1.11";
    extern const char* const UnityVersionSuffix = "f1";
    extern const UInt32 UnityVersionVer = 2022;
    extern const UInt32 UnityVersionMajor = 1;
    extern const UInt32 UnityVersionMinor = 11;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2022.1.11f1_09bebd6e9324";
    extern const char* const UnityVersionUnderHash_Verbose = "2022.1.11f1_09bebd6e9324";
    extern const char* const UnityVersionUnderHash_WithParens = "2022.1.11f1 (09bebd6e9324)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 638653;

    extern const UInt64 UnityVersionDate = 1658414448;
    extern const char* const UnityVersionBranch = "2022.1/staging";
    extern const char* const UnityVersionDisplay = "2022.1.11f1";
    extern const char* const UnityVersionDisplay_Verbose = "2022.1.11f1.3452";
    extern const char* const UnityVersionRevision = "09bebd6e9324";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2022.1.11f1 (09bebd6e9324)";
    extern const wchar_t* const L_UnityVersion = L"2022.1.11f1";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies ApS"
    #define UNITY_COPYRIGHT "(c) 2022 Unity Technologies ApS. All rights reserved."
    #define UNITY_VERSION_VER 2022
    #define UNITY_VERSION_MAJ 1
    #define UNITY_VERSION_MIN 11
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2022.1.11f1_09bebd6e9324"
    #define UNITY_VERSION_PARENS_HASH "2022.1.11f1 (09bebd6e9324)"
    #define UNITY_VERSION_BLD 638653
    #define UNITY_VERSION_WIN "2022.1.11.638653"

#endif // !RC_INVOKED
